# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helpers.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="helpers.proto",
    package="exonum",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=_b(
        '\n\rhelpers.proto\x12\x06\x65xonum"\x14\n\x04Hash\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c"\x19\n\tPublicKey\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c"\x19\n\tSignature\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c"#\n\x06\x42itVec\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0b\n\x03len\x18\x02 \x01(\x04\x62\x06proto3'
    ),
)


_HASH = _descriptor.Descriptor(
    name="Hash",
    full_name="exonum.Hash",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="data",
            full_name="exonum.Hash.data",
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b(""),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        )
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=25,
    serialized_end=45,
)


_PUBLICKEY = _descriptor.Descriptor(
    name="PublicKey",
    full_name="exonum.PublicKey",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="data",
            full_name="exonum.PublicKey.data",
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b(""),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        )
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=47,
    serialized_end=72,
)


_SIGNATURE = _descriptor.Descriptor(
    name="Signature",
    full_name="exonum.Signature",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="data",
            full_name="exonum.Signature.data",
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b(""),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        )
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=74,
    serialized_end=99,
)


_BITVEC = _descriptor.Descriptor(
    name="BitVec",
    full_name="exonum.BitVec",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="data",
            full_name="exonum.BitVec.data",
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b(""),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="len",
            full_name="exonum.BitVec.len",
            index=1,
            number=2,
            type=4,
            cpp_type=4,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=101,
    serialized_end=136,
)

DESCRIPTOR.message_types_by_name["Hash"] = _HASH
DESCRIPTOR.message_types_by_name["PublicKey"] = _PUBLICKEY
DESCRIPTOR.message_types_by_name["Signature"] = _SIGNATURE
DESCRIPTOR.message_types_by_name["BitVec"] = _BITVEC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Hash = _reflection.GeneratedProtocolMessageType(
    "Hash",
    (_message.Message,),
    dict(
        DESCRIPTOR=_HASH,
        __module__="helpers_pb2"
        # @@protoc_insertion_point(class_scope:exonum.Hash)
    ),
)
_sym_db.RegisterMessage(Hash)

PublicKey = _reflection.GeneratedProtocolMessageType(
    "PublicKey",
    (_message.Message,),
    dict(
        DESCRIPTOR=_PUBLICKEY,
        __module__="helpers_pb2"
        # @@protoc_insertion_point(class_scope:exonum.PublicKey)
    ),
)
_sym_db.RegisterMessage(PublicKey)

Signature = _reflection.GeneratedProtocolMessageType(
    "Signature",
    (_message.Message,),
    dict(
        DESCRIPTOR=_SIGNATURE,
        __module__="helpers_pb2"
        # @@protoc_insertion_point(class_scope:exonum.Signature)
    ),
)
_sym_db.RegisterMessage(Signature)

BitVec = _reflection.GeneratedProtocolMessageType(
    "BitVec",
    (_message.Message,),
    dict(
        DESCRIPTOR=_BITVEC,
        __module__="helpers_pb2"
        # @@protoc_insertion_point(class_scope:exonum.BitVec)
    ),
)
_sym_db.RegisterMessage(BitVec)


# @@protoc_insertion_point(module_scope)
