# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import helpers_pb2 as helpers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='exonum.examples.cryptocurrency_advanced',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rservice.proto\x12\'exonum.examples.cryptocurrency_advanced\x1a\rhelpers.proto\"G\n\x08Transfer\x12\x1d\n\x02to\x18\x01 \x01(\x0b\x32\x11.exonum.PublicKey\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x04\x12\x0c\n\x04seed\x18\x03 \x01(\x04\"%\n\x05Issue\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x04\x12\x0c\n\x04seed\x18\x02 \x01(\x04\"\x1c\n\x0c\x43reateWallet\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x84\x01\n\x06Wallet\x12\"\n\x07pub_key\x18\x01 \x01(\x0b\x32\x11.exonum.PublicKey\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x04\x12\x13\n\x0bhistory_len\x18\x04 \x01(\x04\x12\"\n\x0chistory_hash\x18\x05 \x01(\x0b\x32\x0c.exonum.Hash\"\x08\n\x06\x43onfigb\x06proto3')
  ,
  dependencies=[helpers__pb2.DESCRIPTOR,])




_TRANSFER = _descriptor.Descriptor(
  name='Transfer',
  full_name='exonum.examples.cryptocurrency_advanced.Transfer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='to', full_name='exonum.examples.cryptocurrency_advanced.Transfer.to', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='exonum.examples.cryptocurrency_advanced.Transfer.amount', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seed', full_name='exonum.examples.cryptocurrency_advanced.Transfer.seed', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=144,
)


_ISSUE = _descriptor.Descriptor(
  name='Issue',
  full_name='exonum.examples.cryptocurrency_advanced.Issue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount', full_name='exonum.examples.cryptocurrency_advanced.Issue.amount', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seed', full_name='exonum.examples.cryptocurrency_advanced.Issue.seed', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=183,
)


_CREATEWALLET = _descriptor.Descriptor(
  name='CreateWallet',
  full_name='exonum.examples.cryptocurrency_advanced.CreateWallet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='exonum.examples.cryptocurrency_advanced.CreateWallet.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=213,
)


_WALLET = _descriptor.Descriptor(
  name='Wallet',
  full_name='exonum.examples.cryptocurrency_advanced.Wallet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pub_key', full_name='exonum.examples.cryptocurrency_advanced.Wallet.pub_key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='exonum.examples.cryptocurrency_advanced.Wallet.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='balance', full_name='exonum.examples.cryptocurrency_advanced.Wallet.balance', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='history_len', full_name='exonum.examples.cryptocurrency_advanced.Wallet.history_len', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='history_hash', full_name='exonum.examples.cryptocurrency_advanced.Wallet.history_hash', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=348,
)


_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='exonum.examples.cryptocurrency_advanced.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=358,
)

_TRANSFER.fields_by_name['to'].message_type = helpers__pb2._PUBLICKEY
_WALLET.fields_by_name['pub_key'].message_type = helpers__pb2._PUBLICKEY
_WALLET.fields_by_name['history_hash'].message_type = helpers__pb2._HASH
DESCRIPTOR.message_types_by_name['Transfer'] = _TRANSFER
DESCRIPTOR.message_types_by_name['Issue'] = _ISSUE
DESCRIPTOR.message_types_by_name['CreateWallet'] = _CREATEWALLET
DESCRIPTOR.message_types_by_name['Wallet'] = _WALLET
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Transfer = _reflection.GeneratedProtocolMessageType('Transfer', (_message.Message,), dict(
  DESCRIPTOR = _TRANSFER,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:exonum.examples.cryptocurrency_advanced.Transfer)
  ))
_sym_db.RegisterMessage(Transfer)

Issue = _reflection.GeneratedProtocolMessageType('Issue', (_message.Message,), dict(
  DESCRIPTOR = _ISSUE,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:exonum.examples.cryptocurrency_advanced.Issue)
  ))
_sym_db.RegisterMessage(Issue)

CreateWallet = _reflection.GeneratedProtocolMessageType('CreateWallet', (_message.Message,), dict(
  DESCRIPTOR = _CREATEWALLET,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:exonum.examples.cryptocurrency_advanced.CreateWallet)
  ))
_sym_db.RegisterMessage(CreateWallet)

Wallet = _reflection.GeneratedProtocolMessageType('Wallet', (_message.Message,), dict(
  DESCRIPTOR = _WALLET,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:exonum.examples.cryptocurrency_advanced.Wallet)
  ))
_sym_db.RegisterMessage(Wallet)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), dict(
  DESCRIPTOR = _CONFIG,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:exonum.examples.cryptocurrency_advanced.Config)
  ))
_sym_db.RegisterMessage(Config)


# @@protoc_insertion_point(module_scope)
