# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exonum/runtime/errors.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='exonum/runtime/errors.proto',
  package='exonum.runtime',
  syntax='proto3',
  serialized_options=b'\n com.exonum.messages.core.runtime',
  serialized_pb=b'\n\x1b\x65xonum/runtime/errors.proto\x12\x0e\x65xonum.runtime\x1a\x1bgoogle/protobuf/empty.proto\"\x9a\x02\n\x0e\x45xecutionError\x12\'\n\x04kind\x18\x01 \x01(\x0e\x32\x19.exonum.runtime.ErrorKind\x12\x0c\n\x04\x63ode\x18\x02 \x01(\r\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x14\n\nruntime_id\x18\x04 \x01(\rH\x00\x12/\n\rno_runtime_id\x18\x05 \x01(\x0b\x32\x16.google.protobuf.EmptyH\x00\x12-\n\tcall_site\x18\x06 \x01(\x0b\x32\x18.exonum.runtime.CallSiteH\x01\x12.\n\x0cno_call_site\x18\x07 \x01(\x0b\x32\x16.google.protobuf.EmptyH\x01\x42\t\n\x07runtimeB\x0b\n\tcall_info\"\xd9\x01\n\x08\x43\x61llSite\x12\x30\n\tcall_type\x18\x01 \x01(\x0e\x32\x1d.exonum.runtime.CallSite.Type\x12\x13\n\x0binstance_id\x18\x02 \x01(\r\x12\x11\n\tmethod_id\x18\x03 \x01(\r\x12\x11\n\tinterface\x18\x04 \x01(\t\"`\n\x04Type\x12\n\n\x06METHOD\x10\x00\x12\x0f\n\x0b\x43ONSTRUCTOR\x10\x01\x12\x17\n\x13\x42\x45\x46ORE_TRANSACTIONS\x10\x02\x12\x16\n\x12\x41\x46TER_TRANSACTIONS\x10\x03\x12\n\n\x06RESUME\x10\x04\"r\n\x0f\x45xecutionStatus\x12$\n\x02ok\x18\x01 \x01(\x0b\x32\x16.google.protobuf.EmptyH\x00\x12/\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1e.exonum.runtime.ExecutionErrorH\x00\x42\x08\n\x06result*K\n\tErrorKind\x12\x0e\n\nUNEXPECTED\x10\x00\x12\x08\n\x04\x43ORE\x10\x01\x12\x0b\n\x07RUNTIME\x10\x02\x12\x0b\n\x07SERVICE\x10\x03\x12\n\n\x06\x43OMMON\x10\x04\x42\"\n com.exonum.messages.core.runtimeb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])

_ERRORKIND = _descriptor.EnumDescriptor(
  name='ErrorKind',
  full_name='exonum.runtime.ErrorKind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNEXPECTED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CORE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNTIME', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVICE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMMON', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=697,
  serialized_end=772,
)
_sym_db.RegisterEnumDescriptor(_ERRORKIND)

ErrorKind = enum_type_wrapper.EnumTypeWrapper(_ERRORKIND)
UNEXPECTED = 0
CORE = 1
RUNTIME = 2
SERVICE = 3
COMMON = 4


_CALLSITE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='exonum.runtime.CallSite.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='METHOD', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONSTRUCTOR', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BEFORE_TRANSACTIONS', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AFTER_TRANSACTIONS', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESUME', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=483,
  serialized_end=579,
)
_sym_db.RegisterEnumDescriptor(_CALLSITE_TYPE)


_EXECUTIONERROR = _descriptor.Descriptor(
  name='ExecutionError',
  full_name='exonum.runtime.ExecutionError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='kind', full_name='exonum.runtime.ExecutionError.kind', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='exonum.runtime.ExecutionError.code', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='exonum.runtime.ExecutionError.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='runtime_id', full_name='exonum.runtime.ExecutionError.runtime_id', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='no_runtime_id', full_name='exonum.runtime.ExecutionError.no_runtime_id', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='call_site', full_name='exonum.runtime.ExecutionError.call_site', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='no_call_site', full_name='exonum.runtime.ExecutionError.no_call_site', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='runtime', full_name='exonum.runtime.ExecutionError.runtime',
      index=0, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='call_info', full_name='exonum.runtime.ExecutionError.call_info',
      index=1, containing_type=None, fields=[]),
  ],
  serialized_start=77,
  serialized_end=359,
)


_CALLSITE = _descriptor.Descriptor(
  name='CallSite',
  full_name='exonum.runtime.CallSite',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='call_type', full_name='exonum.runtime.CallSite.call_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='exonum.runtime.CallSite.instance_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method_id', full_name='exonum.runtime.CallSite.method_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interface', full_name='exonum.runtime.CallSite.interface', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CALLSITE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=579,
)


_EXECUTIONSTATUS = _descriptor.Descriptor(
  name='ExecutionStatus',
  full_name='exonum.runtime.ExecutionStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='exonum.runtime.ExecutionStatus.ok', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='exonum.runtime.ExecutionStatus.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='result', full_name='exonum.runtime.ExecutionStatus.result',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=581,
  serialized_end=695,
)

_EXECUTIONERROR.fields_by_name['kind'].enum_type = _ERRORKIND
_EXECUTIONERROR.fields_by_name['no_runtime_id'].message_type = google_dot_protobuf_dot_empty__pb2._EMPTY
_EXECUTIONERROR.fields_by_name['call_site'].message_type = _CALLSITE
_EXECUTIONERROR.fields_by_name['no_call_site'].message_type = google_dot_protobuf_dot_empty__pb2._EMPTY
_EXECUTIONERROR.oneofs_by_name['runtime'].fields.append(
  _EXECUTIONERROR.fields_by_name['runtime_id'])
_EXECUTIONERROR.fields_by_name['runtime_id'].containing_oneof = _EXECUTIONERROR.oneofs_by_name['runtime']
_EXECUTIONERROR.oneofs_by_name['runtime'].fields.append(
  _EXECUTIONERROR.fields_by_name['no_runtime_id'])
_EXECUTIONERROR.fields_by_name['no_runtime_id'].containing_oneof = _EXECUTIONERROR.oneofs_by_name['runtime']
_EXECUTIONERROR.oneofs_by_name['call_info'].fields.append(
  _EXECUTIONERROR.fields_by_name['call_site'])
_EXECUTIONERROR.fields_by_name['call_site'].containing_oneof = _EXECUTIONERROR.oneofs_by_name['call_info']
_EXECUTIONERROR.oneofs_by_name['call_info'].fields.append(
  _EXECUTIONERROR.fields_by_name['no_call_site'])
_EXECUTIONERROR.fields_by_name['no_call_site'].containing_oneof = _EXECUTIONERROR.oneofs_by_name['call_info']
_CALLSITE.fields_by_name['call_type'].enum_type = _CALLSITE_TYPE
_CALLSITE_TYPE.containing_type = _CALLSITE
_EXECUTIONSTATUS.fields_by_name['ok'].message_type = google_dot_protobuf_dot_empty__pb2._EMPTY
_EXECUTIONSTATUS.fields_by_name['error'].message_type = _EXECUTIONERROR
_EXECUTIONSTATUS.oneofs_by_name['result'].fields.append(
  _EXECUTIONSTATUS.fields_by_name['ok'])
_EXECUTIONSTATUS.fields_by_name['ok'].containing_oneof = _EXECUTIONSTATUS.oneofs_by_name['result']
_EXECUTIONSTATUS.oneofs_by_name['result'].fields.append(
  _EXECUTIONSTATUS.fields_by_name['error'])
_EXECUTIONSTATUS.fields_by_name['error'].containing_oneof = _EXECUTIONSTATUS.oneofs_by_name['result']
DESCRIPTOR.message_types_by_name['ExecutionError'] = _EXECUTIONERROR
DESCRIPTOR.message_types_by_name['CallSite'] = _CALLSITE
DESCRIPTOR.message_types_by_name['ExecutionStatus'] = _EXECUTIONSTATUS
DESCRIPTOR.enum_types_by_name['ErrorKind'] = _ERRORKIND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExecutionError = _reflection.GeneratedProtocolMessageType('ExecutionError', (_message.Message,), {
  'DESCRIPTOR' : _EXECUTIONERROR,
  '__module__' : 'exonum.runtime.errors_pb2'
  # @@protoc_insertion_point(class_scope:exonum.runtime.ExecutionError)
  })
_sym_db.RegisterMessage(ExecutionError)

CallSite = _reflection.GeneratedProtocolMessageType('CallSite', (_message.Message,), {
  'DESCRIPTOR' : _CALLSITE,
  '__module__' : 'exonum.runtime.errors_pb2'
  # @@protoc_insertion_point(class_scope:exonum.runtime.CallSite)
  })
_sym_db.RegisterMessage(CallSite)

ExecutionStatus = _reflection.GeneratedProtocolMessageType('ExecutionStatus', (_message.Message,), {
  'DESCRIPTOR' : _EXECUTIONSTATUS,
  '__module__' : 'exonum.runtime.errors_pb2'
  # @@protoc_insertion_point(class_scope:exonum.runtime.ExecutionStatus)
  })
_sym_db.RegisterMessage(ExecutionStatus)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
