# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exonum/common/bit_vec.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='exonum/common/bit_vec.proto',
  package='exonum.common',
  syntax='proto3',
  serialized_options=b'\n\032com.exonum.messages.common',
  serialized_pb=b'\n\x1b\x65xonum/common/bit_vec.proto\x12\rexonum.common\"#\n\x06\x42itVec\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0b\n\x03len\x18\x02 \x01(\x04\x42\x1c\n\x1a\x63om.exonum.messages.commonb\x06proto3'
)




_BITVEC = _descriptor.Descriptor(
  name='BitVec',
  full_name='exonum.common.BitVec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='exonum.common.BitVec.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='len', full_name='exonum.common.BitVec.len', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['BitVec'] = _BITVEC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BitVec = _reflection.GeneratedProtocolMessageType('BitVec', (_message.Message,), {
  'DESCRIPTOR' : _BITVEC,
  '__module__' : 'exonum.common.bit_vec_pb2'
  # @@protoc_insertion_point(class_scope:exonum.common.BitVec)
  })
_sym_db.RegisterMessage(BitVec)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
