# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exonum/proof/map_proof.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..crypto import types_pb2 as exonum_dot_crypto_dot_types__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='exonum/proof/map_proof.proto',
  package='exonum.proof',
  syntax='proto3',
  serialized_options=b'\n\031com.exonum.messages.proof',
  serialized_pb=b'\n\x1c\x65xonum/proof/map_proof.proto\x12\x0c\x65xonum.proof\x1a\x19\x65xonum/crypto/types.proto\x1a\x1bgoogle/protobuf/empty.proto\"d\n\x08MapProof\x12,\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1b.exonum.proof.OptionalEntry\x12*\n\x05proof\x18\x02 \x03(\x0b\x32\x1b.exonum.proof.MapProofEntry\"h\n\rOptionalEntry\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\x0f\n\x05value\x18\x02 \x01(\x0cH\x00\x12*\n\x08no_value\x18\x03 \x01(\x0b\x32\x16.google.protobuf.EmptyH\x00\x42\r\n\x0bmaybe_value\"V\n\rMapProofEntry\x12\x0c\n\x04path\x18\x01 \x01(\x0c\x12!\n\x04hash\x18\x02 \x01(\x0b\x32\x13.exonum.crypto.Hash\x12\x14\n\x0cpath_padding\x18\x03 \x01(\rB\x1b\n\x19\x63om.exonum.messages.proofb\x06proto3'
  ,
  dependencies=[exonum_dot_crypto_dot_types__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_MAPPROOF = _descriptor.Descriptor(
  name='MapProof',
  full_name='exonum.proof.MapProof',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='exonum.proof.MapProof.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proof', full_name='exonum.proof.MapProof.proof', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=202,
)


_OPTIONALENTRY = _descriptor.Descriptor(
  name='OptionalEntry',
  full_name='exonum.proof.OptionalEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='exonum.proof.OptionalEntry.key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='exonum.proof.OptionalEntry.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='no_value', full_name='exonum.proof.OptionalEntry.no_value', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='maybe_value', full_name='exonum.proof.OptionalEntry.maybe_value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=204,
  serialized_end=308,
)


_MAPPROOFENTRY = _descriptor.Descriptor(
  name='MapProofEntry',
  full_name='exonum.proof.MapProofEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='exonum.proof.MapProofEntry.path', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash', full_name='exonum.proof.MapProofEntry.hash', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path_padding', full_name='exonum.proof.MapProofEntry.path_padding', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=396,
)

_MAPPROOF.fields_by_name['entries'].message_type = _OPTIONALENTRY
_MAPPROOF.fields_by_name['proof'].message_type = _MAPPROOFENTRY
_OPTIONALENTRY.fields_by_name['no_value'].message_type = google_dot_protobuf_dot_empty__pb2._EMPTY
_OPTIONALENTRY.oneofs_by_name['maybe_value'].fields.append(
  _OPTIONALENTRY.fields_by_name['value'])
_OPTIONALENTRY.fields_by_name['value'].containing_oneof = _OPTIONALENTRY.oneofs_by_name['maybe_value']
_OPTIONALENTRY.oneofs_by_name['maybe_value'].fields.append(
  _OPTIONALENTRY.fields_by_name['no_value'])
_OPTIONALENTRY.fields_by_name['no_value'].containing_oneof = _OPTIONALENTRY.oneofs_by_name['maybe_value']
_MAPPROOFENTRY.fields_by_name['hash'].message_type = exonum_dot_crypto_dot_types__pb2._HASH
DESCRIPTOR.message_types_by_name['MapProof'] = _MAPPROOF
DESCRIPTOR.message_types_by_name['OptionalEntry'] = _OPTIONALENTRY
DESCRIPTOR.message_types_by_name['MapProofEntry'] = _MAPPROOFENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MapProof = _reflection.GeneratedProtocolMessageType('MapProof', (_message.Message,), {
  'DESCRIPTOR' : _MAPPROOF,
  '__module__' : 'exonum.proof.map_proof_pb2'
  # @@protoc_insertion_point(class_scope:exonum.proof.MapProof)
  })
_sym_db.RegisterMessage(MapProof)

OptionalEntry = _reflection.GeneratedProtocolMessageType('OptionalEntry', (_message.Message,), {
  'DESCRIPTOR' : _OPTIONALENTRY,
  '__module__' : 'exonum.proof.map_proof_pb2'
  # @@protoc_insertion_point(class_scope:exonum.proof.OptionalEntry)
  })
_sym_db.RegisterMessage(OptionalEntry)

MapProofEntry = _reflection.GeneratedProtocolMessageType('MapProofEntry', (_message.Message,), {
  'DESCRIPTOR' : _MAPPROOFENTRY,
  '__module__' : 'exonum.proof.map_proof_pb2'
  # @@protoc_insertion_point(class_scope:exonum.proof.MapProofEntry)
  })
_sym_db.RegisterMessage(MapProofEntry)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
