# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exonum/crypto/types.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='exonum/crypto/types.proto',
  package='exonum.crypto',
  syntax='proto3',
  serialized_options=b'\n\032com.exonum.messages.crypto',
  serialized_pb=b'\n\x19\x65xonum/crypto/types.proto\x12\rexonum.crypto\"\x14\n\x04Hash\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x19\n\tPublicKey\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x19\n\tSignature\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x42\x1c\n\x1a\x63om.exonum.messages.cryptob\x06proto3'
)




_HASH = _descriptor.Descriptor(
  name='Hash',
  full_name='exonum.crypto.Hash',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='exonum.crypto.Hash.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=64,
)


_PUBLICKEY = _descriptor.Descriptor(
  name='PublicKey',
  full_name='exonum.crypto.PublicKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='exonum.crypto.PublicKey.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=91,
)


_SIGNATURE = _descriptor.Descriptor(
  name='Signature',
  full_name='exonum.crypto.Signature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='exonum.crypto.Signature.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=118,
)

DESCRIPTOR.message_types_by_name['Hash'] = _HASH
DESCRIPTOR.message_types_by_name['PublicKey'] = _PUBLICKEY
DESCRIPTOR.message_types_by_name['Signature'] = _SIGNATURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Hash = _reflection.GeneratedProtocolMessageType('Hash', (_message.Message,), {
  'DESCRIPTOR' : _HASH,
  '__module__' : 'exonum.crypto.types_pb2'
  # @@protoc_insertion_point(class_scope:exonum.crypto.Hash)
  })
_sym_db.RegisterMessage(Hash)

PublicKey = _reflection.GeneratedProtocolMessageType('PublicKey', (_message.Message,), {
  'DESCRIPTOR' : _PUBLICKEY,
  '__module__' : 'exonum.crypto.types_pb2'
  # @@protoc_insertion_point(class_scope:exonum.crypto.PublicKey)
  })
_sym_db.RegisterMessage(PublicKey)

Signature = _reflection.GeneratedProtocolMessageType('Signature', (_message.Message,), {
  'DESCRIPTOR' : _SIGNATURE,
  '__module__' : 'exonum.crypto.types_pb2'
  # @@protoc_insertion_point(class_scope:exonum.crypto.Signature)
  })
_sym_db.RegisterMessage(Signature)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
