# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exonum/runtime/auth.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..crypto import types_pb2 as exonum_dot_crypto_dot_types__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='exonum/runtime/auth.proto',
  package='exonum.runtime',
  syntax='proto3',
  serialized_options=b'\n com.exonum.messages.core.runtime',
  serialized_pb=b'\n\x19\x65xonum/runtime/auth.proto\x12\x0e\x65xonum.runtime\x1a\x19\x65xonum/crypto/types.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x8f\x01\n\x06\x43\x61ller\x12\x36\n\x12transaction_author\x18\x01 \x01(\x0b\x32\x18.exonum.crypto.PublicKeyH\x00\x12\x15\n\x0binstance_id\x18\x02 \x01(\rH\x00\x12,\n\nblockchain\x18\x03 \x01(\x0b\x32\x16.google.protobuf.EmptyH\x00\x42\x08\n\x06\x63\x61llerB\"\n com.exonum.messages.core.runtimeb\x06proto3'
  ,
  dependencies=[exonum_dot_crypto_dot_types__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_CALLER = _descriptor.Descriptor(
  name='Caller',
  full_name='exonum.runtime.Caller',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transaction_author', full_name='exonum.runtime.Caller.transaction_author', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='exonum.runtime.Caller.instance_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blockchain', full_name='exonum.runtime.Caller.blockchain', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='caller', full_name='exonum.runtime.Caller.caller',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=102,
  serialized_end=245,
)

_CALLER.fields_by_name['transaction_author'].message_type = exonum_dot_crypto_dot_types__pb2._PUBLICKEY
_CALLER.fields_by_name['blockchain'].message_type = google_dot_protobuf_dot_empty__pb2._EMPTY
_CALLER.oneofs_by_name['caller'].fields.append(
  _CALLER.fields_by_name['transaction_author'])
_CALLER.fields_by_name['transaction_author'].containing_oneof = _CALLER.oneofs_by_name['caller']
_CALLER.oneofs_by_name['caller'].fields.append(
  _CALLER.fields_by_name['instance_id'])
_CALLER.fields_by_name['instance_id'].containing_oneof = _CALLER.oneofs_by_name['caller']
_CALLER.oneofs_by_name['caller'].fields.append(
  _CALLER.fields_by_name['blockchain'])
_CALLER.fields_by_name['blockchain'].containing_oneof = _CALLER.oneofs_by_name['caller']
DESCRIPTOR.message_types_by_name['Caller'] = _CALLER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Caller = _reflection.GeneratedProtocolMessageType('Caller', (_message.Message,), {
  'DESCRIPTOR' : _CALLER,
  '__module__' : 'exonum.runtime.auth_pb2'
  # @@protoc_insertion_point(class_scope:exonum.runtime.Caller)
  })
_sym_db.RegisterMessage(Caller)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
