# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exonum/runtime/base.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='exonum/runtime/base.proto',
  package='exonum.runtime',
  syntax='proto3',
  serialized_options=b'\n com.exonum.messages.core.runtime',
  serialized_pb=b'\n\x19\x65xonum/runtime/base.proto\x12\x0e\x65xonum.runtime\"2\n\x08\x43\x61llInfo\x12\x13\n\x0binstance_id\x18\x01 \x01(\r\x12\x11\n\tmethod_id\x18\x02 \x01(\r\"G\n\x05\x41nyTx\x12+\n\tcall_info\x18\x01 \x01(\x0b\x32\x18.exonum.runtime.CallInfo\x12\x11\n\targuments\x18\x02 \x01(\x0c\"?\n\nArtifactId\x12\x12\n\nruntime_id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\"M\n\x0c\x41rtifactSpec\x12,\n\x08\x61rtifact\x18\x01 \x01(\x0b\x32\x1a.exonum.runtime.ArtifactId\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"V\n\x0cInstanceSpec\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12,\n\x08\x61rtifact\x18\x03 \x01(\x0b\x32\x1a.exonum.runtime.ArtifactIdB\"\n com.exonum.messages.core.runtimeb\x06proto3'
)




_CALLINFO = _descriptor.Descriptor(
  name='CallInfo',
  full_name='exonum.runtime.CallInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='exonum.runtime.CallInfo.instance_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method_id', full_name='exonum.runtime.CallInfo.method_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=95,
)


_ANYTX = _descriptor.Descriptor(
  name='AnyTx',
  full_name='exonum.runtime.AnyTx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='call_info', full_name='exonum.runtime.AnyTx.call_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arguments', full_name='exonum.runtime.AnyTx.arguments', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=168,
)


_ARTIFACTID = _descriptor.Descriptor(
  name='ArtifactId',
  full_name='exonum.runtime.ArtifactId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='runtime_id', full_name='exonum.runtime.ArtifactId.runtime_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='exonum.runtime.ArtifactId.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='exonum.runtime.ArtifactId.version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=233,
)


_ARTIFACTSPEC = _descriptor.Descriptor(
  name='ArtifactSpec',
  full_name='exonum.runtime.ArtifactSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='artifact', full_name='exonum.runtime.ArtifactSpec.artifact', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='exonum.runtime.ArtifactSpec.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=312,
)


_INSTANCESPEC = _descriptor.Descriptor(
  name='InstanceSpec',
  full_name='exonum.runtime.InstanceSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='exonum.runtime.InstanceSpec.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='exonum.runtime.InstanceSpec.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='artifact', full_name='exonum.runtime.InstanceSpec.artifact', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=400,
)

_ANYTX.fields_by_name['call_info'].message_type = _CALLINFO
_ARTIFACTSPEC.fields_by_name['artifact'].message_type = _ARTIFACTID
_INSTANCESPEC.fields_by_name['artifact'].message_type = _ARTIFACTID
DESCRIPTOR.message_types_by_name['CallInfo'] = _CALLINFO
DESCRIPTOR.message_types_by_name['AnyTx'] = _ANYTX
DESCRIPTOR.message_types_by_name['ArtifactId'] = _ARTIFACTID
DESCRIPTOR.message_types_by_name['ArtifactSpec'] = _ARTIFACTSPEC
DESCRIPTOR.message_types_by_name['InstanceSpec'] = _INSTANCESPEC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CallInfo = _reflection.GeneratedProtocolMessageType('CallInfo', (_message.Message,), {
  'DESCRIPTOR' : _CALLINFO,
  '__module__' : 'exonum.runtime.base_pb2'
  # @@protoc_insertion_point(class_scope:exonum.runtime.CallInfo)
  })
_sym_db.RegisterMessage(CallInfo)

AnyTx = _reflection.GeneratedProtocolMessageType('AnyTx', (_message.Message,), {
  'DESCRIPTOR' : _ANYTX,
  '__module__' : 'exonum.runtime.base_pb2'
  # @@protoc_insertion_point(class_scope:exonum.runtime.AnyTx)
  })
_sym_db.RegisterMessage(AnyTx)

ArtifactId = _reflection.GeneratedProtocolMessageType('ArtifactId', (_message.Message,), {
  'DESCRIPTOR' : _ARTIFACTID,
  '__module__' : 'exonum.runtime.base_pb2'
  # @@protoc_insertion_point(class_scope:exonum.runtime.ArtifactId)
  })
_sym_db.RegisterMessage(ArtifactId)

ArtifactSpec = _reflection.GeneratedProtocolMessageType('ArtifactSpec', (_message.Message,), {
  'DESCRIPTOR' : _ARTIFACTSPEC,
  '__module__' : 'exonum.runtime.base_pb2'
  # @@protoc_insertion_point(class_scope:exonum.runtime.ArtifactSpec)
  })
_sym_db.RegisterMessage(ArtifactSpec)

InstanceSpec = _reflection.GeneratedProtocolMessageType('InstanceSpec', (_message.Message,), {
  'DESCRIPTOR' : _INSTANCESPEC,
  '__module__' : 'exonum.runtime.base_pb2'
  # @@protoc_insertion_point(class_scope:exonum.runtime.InstanceSpec)
  })
_sym_db.RegisterMessage(InstanceSpec)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
