# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exonum/messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from .crypto import types_pb2 as exonum_dot_crypto_dot_types__pb2
from .runtime import base_pb2 as exonum_dot_runtime_dot_base__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='exonum/messages.proto',
  package='exonum',
  syntax='proto3',
  serialized_options=b'\n\030com.exonum.messages.core',
  serialized_pb=b'\n\x15\x65xonum/messages.proto\x12\x06\x65xonum\x1a\x19\x65xonum/crypto/types.proto\x1a\x19\x65xonum/runtime/base.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"w\n\rSignedMessage\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12(\n\x06\x61uthor\x18\x02 \x01(\x0b\x32\x18.exonum.crypto.PublicKey\x12+\n\tsignature\x18\x03 \x01(\x0b\x32\x18.exonum.crypto.Signature\"f\n\x0b\x43oreMessage\x12\'\n\x06\x61ny_tx\x18\x01 \x01(\x0b\x32\x15.exonum.runtime.AnyTxH\x00\x12&\n\tprecommit\x18\x02 \x01(\x0b\x32\x11.exonum.PrecommitH\x00\x42\x06\n\x04kind\"\xbb\x01\n\tPrecommit\x12\x11\n\tvalidator\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\x04\x12\r\n\x05round\x18\x03 \x01(\r\x12)\n\x0cpropose_hash\x18\x04 \x01(\x0b\x32\x13.exonum.crypto.Hash\x12\'\n\nblock_hash\x18\x05 \x01(\x0b\x32\x13.exonum.crypto.Hash\x12(\n\x04time\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x1a\n\x18\x63om.exonum.messages.coreb\x06proto3'
  ,
  dependencies=[exonum_dot_crypto_dot_types__pb2.DESCRIPTOR,exonum_dot_runtime_dot_base__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_SIGNEDMESSAGE = _descriptor.Descriptor(
  name='SignedMessage',
  full_name='exonum.SignedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='exonum.SignedMessage.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='author', full_name='exonum.SignedMessage.author', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='exonum.SignedMessage.signature', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=239,
)


_COREMESSAGE = _descriptor.Descriptor(
  name='CoreMessage',
  full_name='exonum.CoreMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='any_tx', full_name='exonum.CoreMessage.any_tx', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='precommit', full_name='exonum.CoreMessage.precommit', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='kind', full_name='exonum.CoreMessage.kind',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=241,
  serialized_end=343,
)


_PRECOMMIT = _descriptor.Descriptor(
  name='Precommit',
  full_name='exonum.Precommit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='validator', full_name='exonum.Precommit.validator', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='exonum.Precommit.height', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='round', full_name='exonum.Precommit.round', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='propose_hash', full_name='exonum.Precommit.propose_hash', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_hash', full_name='exonum.Precommit.block_hash', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='exonum.Precommit.time', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=346,
  serialized_end=533,
)

_SIGNEDMESSAGE.fields_by_name['author'].message_type = exonum_dot_crypto_dot_types__pb2._PUBLICKEY
_SIGNEDMESSAGE.fields_by_name['signature'].message_type = exonum_dot_crypto_dot_types__pb2._SIGNATURE
_COREMESSAGE.fields_by_name['any_tx'].message_type = exonum_dot_runtime_dot_base__pb2._ANYTX
_COREMESSAGE.fields_by_name['precommit'].message_type = _PRECOMMIT
_COREMESSAGE.oneofs_by_name['kind'].fields.append(
  _COREMESSAGE.fields_by_name['any_tx'])
_COREMESSAGE.fields_by_name['any_tx'].containing_oneof = _COREMESSAGE.oneofs_by_name['kind']
_COREMESSAGE.oneofs_by_name['kind'].fields.append(
  _COREMESSAGE.fields_by_name['precommit'])
_COREMESSAGE.fields_by_name['precommit'].containing_oneof = _COREMESSAGE.oneofs_by_name['kind']
_PRECOMMIT.fields_by_name['propose_hash'].message_type = exonum_dot_crypto_dot_types__pb2._HASH
_PRECOMMIT.fields_by_name['block_hash'].message_type = exonum_dot_crypto_dot_types__pb2._HASH
_PRECOMMIT.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['SignedMessage'] = _SIGNEDMESSAGE
DESCRIPTOR.message_types_by_name['CoreMessage'] = _COREMESSAGE
DESCRIPTOR.message_types_by_name['Precommit'] = _PRECOMMIT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SignedMessage = _reflection.GeneratedProtocolMessageType('SignedMessage', (_message.Message,), {
  'DESCRIPTOR' : _SIGNEDMESSAGE,
  '__module__' : 'exonum.messages_pb2'
  # @@protoc_insertion_point(class_scope:exonum.SignedMessage)
  })
_sym_db.RegisterMessage(SignedMessage)

CoreMessage = _reflection.GeneratedProtocolMessageType('CoreMessage', (_message.Message,), {
  'DESCRIPTOR' : _COREMESSAGE,
  '__module__' : 'exonum.messages_pb2'
  # @@protoc_insertion_point(class_scope:exonum.CoreMessage)
  })
_sym_db.RegisterMessage(CoreMessage)

Precommit = _reflection.GeneratedProtocolMessageType('Precommit', (_message.Message,), {
  'DESCRIPTOR' : _PRECOMMIT,
  '__module__' : 'exonum.messages_pb2'
  # @@protoc_insertion_point(class_scope:exonum.Precommit)
  })
_sym_db.RegisterMessage(Precommit)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
