# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exonum/proof/list_proof.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..crypto import types_pb2 as exonum_dot_crypto_dot_types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='exonum/proof/list_proof.proto',
  package='exonum.proof',
  syntax='proto3',
  serialized_options=b'\n\031com.exonum.messages.proof',
  serialized_pb=b'\n\x1d\x65xonum/proof/list_proof.proto\x12\x0c\x65xonum.proof\x1a\x19\x65xonum/crypto/types.proto\"t\n\tListProof\x12(\n\x05proof\x18\x01 \x03(\x0b\x32\x19.exonum.proof.HashedEntry\x12-\n\x07\x65ntries\x18\x02 \x03(\x0b\x32\x1c.exonum.proof.ListProofEntry\x12\x0e\n\x06length\x18\x03 \x01(\x04\"Y\n\x0bHashedEntry\x12\'\n\x03key\x18\x01 \x01(\x0b\x32\x1a.exonum.proof.ProofListKey\x12!\n\x04hash\x18\x02 \x01(\x0b\x32\x13.exonum.crypto.Hash\".\n\x0eListProofEntry\x12\r\n\x05index\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\x0c\"-\n\x0cProofListKey\x12\r\n\x05index\x18\x01 \x01(\x04\x12\x0e\n\x06height\x18\x02 \x01(\rB\x1b\n\x19\x63om.exonum.messages.proofb\x06proto3'
  ,
  dependencies=[exonum_dot_crypto_dot_types__pb2.DESCRIPTOR,])




_LISTPROOF = _descriptor.Descriptor(
  name='ListProof',
  full_name='exonum.proof.ListProof',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proof', full_name='exonum.proof.ListProof.proof', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entries', full_name='exonum.proof.ListProof.entries', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length', full_name='exonum.proof.ListProof.length', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=190,
)


_HASHEDENTRY = _descriptor.Descriptor(
  name='HashedEntry',
  full_name='exonum.proof.HashedEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='exonum.proof.HashedEntry.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash', full_name='exonum.proof.HashedEntry.hash', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=281,
)


_LISTPROOFENTRY = _descriptor.Descriptor(
  name='ListProofEntry',
  full_name='exonum.proof.ListProofEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='exonum.proof.ListProofEntry.index', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='exonum.proof.ListProofEntry.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=329,
)


_PROOFLISTKEY = _descriptor.Descriptor(
  name='ProofListKey',
  full_name='exonum.proof.ProofListKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='exonum.proof.ProofListKey.index', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='exonum.proof.ProofListKey.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=376,
)

_LISTPROOF.fields_by_name['proof'].message_type = _HASHEDENTRY
_LISTPROOF.fields_by_name['entries'].message_type = _LISTPROOFENTRY
_HASHEDENTRY.fields_by_name['key'].message_type = _PROOFLISTKEY
_HASHEDENTRY.fields_by_name['hash'].message_type = exonum_dot_crypto_dot_types__pb2._HASH
DESCRIPTOR.message_types_by_name['ListProof'] = _LISTPROOF
DESCRIPTOR.message_types_by_name['HashedEntry'] = _HASHEDENTRY
DESCRIPTOR.message_types_by_name['ListProofEntry'] = _LISTPROOFENTRY
DESCRIPTOR.message_types_by_name['ProofListKey'] = _PROOFLISTKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListProof = _reflection.GeneratedProtocolMessageType('ListProof', (_message.Message,), {
  'DESCRIPTOR' : _LISTPROOF,
  '__module__' : 'exonum.proof.list_proof_pb2'
  # @@protoc_insertion_point(class_scope:exonum.proof.ListProof)
  })
_sym_db.RegisterMessage(ListProof)

HashedEntry = _reflection.GeneratedProtocolMessageType('HashedEntry', (_message.Message,), {
  'DESCRIPTOR' : _HASHEDENTRY,
  '__module__' : 'exonum.proof.list_proof_pb2'
  # @@protoc_insertion_point(class_scope:exonum.proof.HashedEntry)
  })
_sym_db.RegisterMessage(HashedEntry)

ListProofEntry = _reflection.GeneratedProtocolMessageType('ListProofEntry', (_message.Message,), {
  'DESCRIPTOR' : _LISTPROOFENTRY,
  '__module__' : 'exonum.proof.list_proof_pb2'
  # @@protoc_insertion_point(class_scope:exonum.proof.ListProofEntry)
  })
_sym_db.RegisterMessage(ListProofEntry)

ProofListKey = _reflection.GeneratedProtocolMessageType('ProofListKey', (_message.Message,), {
  'DESCRIPTOR' : _PROOFLISTKEY,
  '__module__' : 'exonum.proof.list_proof_pb2'
  # @@protoc_insertion_point(class_scope:exonum.proof.ProofListKey)
  })
_sym_db.RegisterMessage(ProofListKey)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
