# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timestamping.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import tests.proto_test.helpers_pb2 as helpers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='timestamping.proto',
  package='exonum.examples.timestamping',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12timestamping.proto\x12\x1c\x65xonum.examples.timestamping\x1a\rhelpers.proto\"T\n\x0bTxTimestamp\x12\"\n\x0c\x63ontent_hash\x18\x01 \x01(\x0b\x32\x0c.exonum.Hash\x12!\n\x06owners\x18\x02 \x03(\x0b\x32\x11.exonum.PublicKeyb\x06proto3')
  ,
  dependencies=[helpers__pb2.DESCRIPTOR,])




_TXTIMESTAMP = _descriptor.Descriptor(
  name='TxTimestamp',
  full_name='exonum.examples.timestamping.TxTimestamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content_hash', full_name='exonum.examples.timestamping.TxTimestamp.content_hash', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owners', full_name='exonum.examples.timestamping.TxTimestamp.owners', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=151,
)

_TXTIMESTAMP.fields_by_name['content_hash'].message_type = helpers__pb2._HASH
_TXTIMESTAMP.fields_by_name['owners'].message_type = helpers__pb2._PUBLICKEY
DESCRIPTOR.message_types_by_name['TxTimestamp'] = _TXTIMESTAMP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TxTimestamp = _reflection.GeneratedProtocolMessageType('TxTimestamp', (_message.Message,), dict(
  DESCRIPTOR = _TXTIMESTAMP,
  __module__ = 'timestamping_pb2'
  # @@protoc_insertion_point(class_scope:exonum.examples.timestamping.TxTimestamp)
  ))
_sym_db.RegisterMessage(TxTimestamp)


# @@protoc_insertion_point(module_scope)
