# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import types_pb2 as types__pb2
from . import key_value_sequence_pb2 as key__value__sequence__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='blockchain.proto',
  package='exonum',
  syntax='proto3',
  serialized_options=b'\n\030com.exonum.core.messages',
  serialized_pb=b'\n\x10\x62lockchain.proto\x12\x06\x65xonum\x1a\x0btypes.proto\x1a\x18key_value_sequence.proto\">\n\x11\x41\x64\x64itionalHeaders\x12)\n\x07headers\x18\x01 \x01(\x0b\x32\x18.exonum.KeyValueSequence\"\x95\x02\n\x05\x42lock\x12\x13\n\x0bproposer_id\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\x04\x12\x10\n\x08tx_count\x18\x03 \x01(\r\x12&\n\tprev_hash\x18\x04 \x01(\x0b\x32\x13.exonum.crypto.Hash\x12$\n\x07tx_hash\x18\x05 \x01(\x0b\x32\x13.exonum.crypto.Hash\x12\'\n\nstate_hash\x18\x06 \x01(\x0b\x32\x13.exonum.crypto.Hash\x12\'\n\nerror_hash\x18\x07 \x01(\x0b\x32\x13.exonum.crypto.Hash\x12\x35\n\x12\x61\x64\x64itional_headers\x18\x08 \x01(\x0b\x32\x19.exonum.AdditionalHeaders\"=\n\nTxLocation\x12\x14\n\x0c\x62lock_height\x18\x01 \x01(\x04\x12\x19\n\x11position_in_block\x18\x02 \x01(\r\"i\n\x0b\x43\x61llInBlock\x12\x15\n\x0btransaction\x18\x01 \x01(\rH\x00\x12\x1d\n\x13\x62\x65\x66ore_transactions\x18\x02 \x01(\rH\x00\x12\x1c\n\x12\x61\x66ter_transactions\x18\x03 \x01(\rH\x00\x42\x06\n\x04\x63\x61ll\"o\n\rValidatorKeys\x12/\n\rconsensus_key\x18\x01 \x01(\x0b\x32\x18.exonum.crypto.PublicKey\x12-\n\x0bservice_key\x18\x02 \x01(\x0b\x32\x18.exonum.crypto.PublicKey\"\x92\x02\n\x06\x43onfig\x12-\n\x0evalidator_keys\x18\x01 \x03(\x0b\x32\x15.exonum.ValidatorKeys\x12\x1b\n\x13\x66irst_round_timeout\x18\x02 \x01(\x04\x12\x16\n\x0estatus_timeout\x18\x03 \x01(\x04\x12\x15\n\rpeers_timeout\x18\x04 \x01(\x04\x12\x17\n\x0ftxs_block_limit\x18\x05 \x01(\r\x12\x17\n\x0fmax_message_len\x18\x06 \x01(\r\x12\x1b\n\x13min_propose_timeout\x18\x07 \x01(\x04\x12\x1b\n\x13max_propose_timeout\x18\x08 \x01(\x04\x12!\n\x19propose_timeout_threshold\x18\t \x01(\rB\x1a\n\x18\x63om.exonum.core.messagesb\x06proto3'
  ,
  dependencies=[types__pb2.DESCRIPTOR,key__value__sequence__pb2.DESCRIPTOR,])




_ADDITIONALHEADERS = _descriptor.Descriptor(
  name='AdditionalHeaders',
  full_name='exonum.AdditionalHeaders',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='headers', full_name='exonum.AdditionalHeaders.headers', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=129,
)


_BLOCK = _descriptor.Descriptor(
  name='Block',
  full_name='exonum.Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proposer_id', full_name='exonum.Block.proposer_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='exonum.Block.height', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tx_count', full_name='exonum.Block.tx_count', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prev_hash', full_name='exonum.Block.prev_hash', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tx_hash', full_name='exonum.Block.tx_hash', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state_hash', full_name='exonum.Block.state_hash', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_hash', full_name='exonum.Block.error_hash', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='additional_headers', full_name='exonum.Block.additional_headers', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=409,
)


_TXLOCATION = _descriptor.Descriptor(
  name='TxLocation',
  full_name='exonum.TxLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='block_height', full_name='exonum.TxLocation.block_height', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position_in_block', full_name='exonum.TxLocation.position_in_block', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=411,
  serialized_end=472,
)


_CALLINBLOCK = _descriptor.Descriptor(
  name='CallInBlock',
  full_name='exonum.CallInBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transaction', full_name='exonum.CallInBlock.transaction', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='before_transactions', full_name='exonum.CallInBlock.before_transactions', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='after_transactions', full_name='exonum.CallInBlock.after_transactions', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='call', full_name='exonum.CallInBlock.call',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=474,
  serialized_end=579,
)


_VALIDATORKEYS = _descriptor.Descriptor(
  name='ValidatorKeys',
  full_name='exonum.ValidatorKeys',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='consensus_key', full_name='exonum.ValidatorKeys.consensus_key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service_key', full_name='exonum.ValidatorKeys.service_key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=581,
  serialized_end=692,
)


_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='exonum.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='validator_keys', full_name='exonum.Config.validator_keys', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='first_round_timeout', full_name='exonum.Config.first_round_timeout', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status_timeout', full_name='exonum.Config.status_timeout', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='peers_timeout', full_name='exonum.Config.peers_timeout', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='txs_block_limit', full_name='exonum.Config.txs_block_limit', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_message_len', full_name='exonum.Config.max_message_len', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_propose_timeout', full_name='exonum.Config.min_propose_timeout', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_propose_timeout', full_name='exonum.Config.max_propose_timeout', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='propose_timeout_threshold', full_name='exonum.Config.propose_timeout_threshold', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=695,
  serialized_end=969,
)

_ADDITIONALHEADERS.fields_by_name['headers'].message_type = key__value__sequence__pb2._KEYVALUESEQUENCE
_BLOCK.fields_by_name['prev_hash'].message_type = types__pb2._HASH
_BLOCK.fields_by_name['tx_hash'].message_type = types__pb2._HASH
_BLOCK.fields_by_name['state_hash'].message_type = types__pb2._HASH
_BLOCK.fields_by_name['error_hash'].message_type = types__pb2._HASH
_BLOCK.fields_by_name['additional_headers'].message_type = _ADDITIONALHEADERS
_CALLINBLOCK.oneofs_by_name['call'].fields.append(
  _CALLINBLOCK.fields_by_name['transaction'])
_CALLINBLOCK.fields_by_name['transaction'].containing_oneof = _CALLINBLOCK.oneofs_by_name['call']
_CALLINBLOCK.oneofs_by_name['call'].fields.append(
  _CALLINBLOCK.fields_by_name['before_transactions'])
_CALLINBLOCK.fields_by_name['before_transactions'].containing_oneof = _CALLINBLOCK.oneofs_by_name['call']
_CALLINBLOCK.oneofs_by_name['call'].fields.append(
  _CALLINBLOCK.fields_by_name['after_transactions'])
_CALLINBLOCK.fields_by_name['after_transactions'].containing_oneof = _CALLINBLOCK.oneofs_by_name['call']
_VALIDATORKEYS.fields_by_name['consensus_key'].message_type = types__pb2._PUBLICKEY
_VALIDATORKEYS.fields_by_name['service_key'].message_type = types__pb2._PUBLICKEY
_CONFIG.fields_by_name['validator_keys'].message_type = _VALIDATORKEYS
DESCRIPTOR.message_types_by_name['AdditionalHeaders'] = _ADDITIONALHEADERS
DESCRIPTOR.message_types_by_name['Block'] = _BLOCK
DESCRIPTOR.message_types_by_name['TxLocation'] = _TXLOCATION
DESCRIPTOR.message_types_by_name['CallInBlock'] = _CALLINBLOCK
DESCRIPTOR.message_types_by_name['ValidatorKeys'] = _VALIDATORKEYS
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AdditionalHeaders = _reflection.GeneratedProtocolMessageType('AdditionalHeaders', (_message.Message,), {
  'DESCRIPTOR' : _ADDITIONALHEADERS,
  '__module__' : 'blockchain_pb2'
  # @@protoc_insertion_point(class_scope:exonum.AdditionalHeaders)
  })
_sym_db.RegisterMessage(AdditionalHeaders)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), {
  'DESCRIPTOR' : _BLOCK,
  '__module__' : 'blockchain_pb2'
  # @@protoc_insertion_point(class_scope:exonum.Block)
  })
_sym_db.RegisterMessage(Block)

TxLocation = _reflection.GeneratedProtocolMessageType('TxLocation', (_message.Message,), {
  'DESCRIPTOR' : _TXLOCATION,
  '__module__' : 'blockchain_pb2'
  # @@protoc_insertion_point(class_scope:exonum.TxLocation)
  })
_sym_db.RegisterMessage(TxLocation)

CallInBlock = _reflection.GeneratedProtocolMessageType('CallInBlock', (_message.Message,), {
  'DESCRIPTOR' : _CALLINBLOCK,
  '__module__' : 'blockchain_pb2'
  # @@protoc_insertion_point(class_scope:exonum.CallInBlock)
  })
_sym_db.RegisterMessage(CallInBlock)

ValidatorKeys = _reflection.GeneratedProtocolMessageType('ValidatorKeys', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATORKEYS,
  '__module__' : 'blockchain_pb2'
  # @@protoc_insertion_point(class_scope:exonum.ValidatorKeys)
  })
_sym_db.RegisterMessage(ValidatorKeys)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), {
  'DESCRIPTOR' : _CONFIG,
  '__module__' : 'blockchain_pb2'
  # @@protoc_insertion_point(class_scope:exonum.Config)
  })
_sym_db.RegisterMessage(Config)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
