# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: key_value_sequence.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='key_value_sequence.proto',
  package='exonum',
  syntax='proto3',
  serialized_options=b'\n\030com.exonum.core.messages',
  serialized_pb=b'\n\x18key_value_sequence.proto\x12\x06\x65xonum\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"3\n\x10KeyValueSequence\x12\x1f\n\x05\x65ntry\x18\x01 \x03(\x0b\x32\x10.exonum.KeyValueB\x1a\n\x18\x63om.exonum.core.messagesb\x06proto3'
)




_KEYVALUE = _descriptor.Descriptor(
  name='KeyValue',
  full_name='exonum.KeyValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='exonum.KeyValue.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='exonum.KeyValue.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=74,
)


_KEYVALUESEQUENCE = _descriptor.Descriptor(
  name='KeyValueSequence',
  full_name='exonum.KeyValueSequence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry', full_name='exonum.KeyValueSequence.entry', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=127,
)

_KEYVALUESEQUENCE.fields_by_name['entry'].message_type = _KEYVALUE
DESCRIPTOR.message_types_by_name['KeyValue'] = _KEYVALUE
DESCRIPTOR.message_types_by_name['KeyValueSequence'] = _KEYVALUESEQUENCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KeyValue = _reflection.GeneratedProtocolMessageType('KeyValue', (_message.Message,), {
  'DESCRIPTOR' : _KEYVALUE,
  '__module__' : 'key_value_sequence_pb2'
  # @@protoc_insertion_point(class_scope:exonum.KeyValue)
  })
_sym_db.RegisterMessage(KeyValue)

KeyValueSequence = _reflection.GeneratedProtocolMessageType('KeyValueSequence', (_message.Message,), {
  'DESCRIPTOR' : _KEYVALUESEQUENCE,
  '__module__' : 'key_value_sequence_pb2'
  # @@protoc_insertion_point(class_scope:exonum.KeyValueSequence)
  })
_sym_db.RegisterMessage(KeyValueSequence)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
